### PR TITLE
Create main.py

### PR DESCRIPTION
**Pull request by InvisiblePro**
# Pull Request: Password Generator in python

## Description
A Python Program for the users to generate strong passwords.

## Changes Made
- Added a Python script for generating passwords.

## Requirements 
- Compatible with python without any modules

## Usage
- Run the script and follow steps as output suggests.

### CODE REVIEW

**Comment by InvisiblePro** [comment]
Thankss buddy for your gratitude and for tagging me on [xenomorphing007/HacktoberFest2k23](https://github.com/xenomorphing007/HacktoberFest2k23)

**Comment by pralinkhaira** [comment]
> Thankss buddy for your gratitude and for tagging me on [xenomorphing007/HacktoberFest2k23](https://github.com/xenomorphing007/HacktoberFest2k23)

Thank You For information!!

**Review by pralinkhaira — APPROVED** [review]
# Review
- Nice Job Buddy!!
- Share and Star the repo!!
- Happy Coding/Contributing :)
- Follow My [LinkedIn](https://www.linkedin.com/in/pralin-khaira-bb462a252/)

**Comment by InvisiblePro** [comment]
Thankss broh!

**Pull request merged**
