### PR TITLE
Update Contributers.md

### PR DESCRIPTION
**Pull request by InvisiblePro**
Profile update in Contributors file

### CODE REVIEW

**Comment by InvisiblePro** [comment]
Heyy! buddy you can also add people as collaborators on you repository, they can do task as approving or viewing a PR or testing programs of PR...

**Comment by pralinkhaira** [comment]
> Heyy! buddy you can also add people as collaborators on you repository, they can do task as approving or viewing a PR or testing programs of PR...

DM discord !! Wanna catchup on this!!

**Review by pralinkhaira — APPROVED** [review]
# Review
- Nice Job Buddy!!
- Share and Star the repo!!
- Happy Coding/Contributing :)
- Follow My [LinkedIn](https://www.linkedin.com/in/pralin-khaira-bb462a252/)

**Comment by InvisiblePro** [comment]
Yea sure
Thanks!

**Pull request merged**
